### ISSUE TITLE
New Icon Add Request

### ISSUE THREAD

**Issue by JayCao7788** [erajasekar/notion-icons#3]
PLEASE CLICK ON PREVIEW TO READ INSTRUCTIONS AND SWITCHBACK WRITE TAB TO PROVIDE DETAILS.

---

### Find Icons you want to add from Icons8

* Go to [Icons8 Material style icons](https://icons8.com/icons/material)
* Search for your icon with keyword. For e.g `facebook`.
* Click on the icon you want and click `Embed HTML Button`.
* Copy name of the icon from last part of img src URL. In URL `https://img.icons8.com/material/24/000000/facebook-new.png`. Icon name is `facebook-new`
* Repeat this for each Icon you want to add and have a list of Icon names.
* For each Icon, if you want it to an associate search keyword, provide a comma-separated tags list.

### List Icon names and tags below.

*REPLACE THIS EXAMPLE WITH YOURS FOR EACH ICON*

name : "battle"
tags : "objects"

**Comment by erajasekar** [comment]
@JayCruiseee Added your icon. Check at https://notion.erajasekar.com/icons
