### ISSUE TITLE
New Icon Add Request

### ISSUE THREAD

**Issue by magicalme** [erajasekar/notion-icons#8]
PLEASE CLICK ON PREVIEW TO READ INSTRUCTIONS AND SWITCHBACK WRITE TAB TO PROVIDE DETAILS.

---

### Find Icons you want to add from Icons8

* Go to [Icons8 Material style icons](https://icons8.com/icons/material)
* Search for your icon with keyword. For e.g `facebook`.
* Click on the icon you want and click `Embed HTML Button`.
* Copy name of the icon from last part of img src URL. In URL `https://img.icons8.com/material/24/000000/facebook-new.png`. Icon name is `facebook-new`
* Repeat this for each Icon you want to add and have a list of Icon names.
* For each Icon, if you want it to an associate search keyword, provide a comma-separated tags list.

### List Icon names and tags below.

*<a href="https://icons8.com/icon/120822/business-network">Business Network icon by Icons8</a>*

name : "Business Network icon by Icons8"
tags : "Networking"

*<a target="_blank" href="https://icons8.com/icon/83764/increase">Increase icon by Icons8</a>*

name: Increase icon by Icons8
tags: SEO

**Comment by erajasekar** [comment]
@magicalme Added those icons. Please check https://notion.erajasekar.com/icons
